// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BeforeClose(arg1) {
  return window['go']['backend']['App']['BeforeClose'](arg1);
}

export function DomReady(arg1) {
  return window['go']['backend']['App']['DomReady'](arg1);
}

export function GetDeviceInformation() {
  return window['go']['backend']['App']['GetDeviceInformation']();
}

export function LoadAvaliableDevices() {
  return window['go']['backend']['App']['LoadAvaliableDevices']();
}

export function LoadDevices(arg1) {
  return window['go']['backend']['App']['LoadDevices'](arg1);
}

export function LoadDevicesPolling() {
  return window['go']['backend']['App']['LoadDevicesPolling']();
}

export function SelectDevice(arg1) {
  return window['go']['backend']['App']['SelectDevice'](arg1);
}

export function Shutdown(arg1) {
  return window['go']['backend']['App']['Shutdown'](arg1);
}

export function UpdateAvaliableDevices(arg1) {
  return window['go']['backend']['App']['UpdateAvaliableDevices'](arg1);
}
