// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';
import {backend} from '../models';

export function BeforeClose(arg1:context.Context):Promise<boolean>;

export function DomReady(arg1:context.Context):Promise<void>;

export function LoadAvaliableDevices():Promise<Array<backend.DeviceInformationJson>>;

export function LoadDevices(arg1:context.Context):Promise<void>;

export function LoadDevicesPolling():Promise<Error>;

export function SelectDevice(arg1:number):Promise<Error>;

export function Shutdown(arg1:context.Context):Promise<void>;

export function UpdateAvaliableDevices(arg1:Array<backend.DeviceInformationJson>):Promise<void>;
