export const back_button_map = new Map<string, string>();
back_button_map.set("INTELLIMOUSE_PRO_BACK_BUTTON_SET_BACK_BUTTON", "Browser Back");
back_button_map.set("INTELLIMOUSE_PRO_BACK_BUTTON_SET_HORIZONTAL_VERTICAL_TOGGLE", "Horizontal Vertical Toggle");
back_button_map.set("INTELLIMOUSE_PRO_BACK_BUTTON_SET_KEY_COMBINATION", "Key Combination");
back_button_map.set("INTELLIMOUSE_PRO_BACK_BUTTON_SET_DPI_SHIFT", "DPI Shift");
back_button_map.set("INTELLIMOUSE_PRO_BACK_BUTTON_SET_INCREASE_DPI", "Increase DPI");
back_button_map.set("INTELLIMOUSE_PRO_BACK_BUTTON_SET_INCREASE_DPI", "Decrease DPI");
back_button_map.set("INTELLIMOUSE_PRO_BACK_BUTTON_SET_MIDDLE_CLICK", "Middle Click");
back_button_map.set("INTELLIMOUSE_PRO_BACK_BUTTON_SET_BROWSER_FORWARD", "Browser Forward");
back_button_map.set("INTELLIMOUSE_PRO_BACK_BUTTON_SET_ALT", "Alt");
back_button_map.set("INTELLIMOUSE_PRO_BACK_BUTTON_SET_CTRL", "Ctrl");
back_button_map.set("INTELLIMOUSE_PRO_BACK_BUTTON_SET_SHIFT", "Shift");
back_button_map.set("INTELLIMOUSE_PRO_BACK_BUTTON_SET_ENTER", "Enter");
