export const button_map = new Map<string, string>();
button_map.set("INTELLIMOUSE_PRO_BUTTON_SET_BACK_BUTTON", "Browser Back");
button_map.set("INTELLIMOUSE_PRO_BUTTON_SET_HORIZONTAL_VERTICAL_TOGGLE", "Horizontal Vertical Toggle");
button_map.set("INTELLIMOUSE_PRO_BUTTON_SET_DPI_SHIFT", "DPI Shift");
button_map.set("INTELLIMOUSE_PRO_BUTTON_SET_INCREASE_DPI", "Increase DPI");
button_map.set("INTELLIMOUSE_PRO_BUTTON_SET_INCREASE_DPI", "Decrease DPI");
button_map.set("INTELLIMOUSE_PRO_BUTTON_SET_MIDDLE_CLICK", "Middle Click");
button_map.set("INTELLIMOUSE_PRO_BUTTON_SET_BROWSER_FORWARD", "Browser Forward");
button_map.set("INTELLIMOUSE_PRO_BUTTON_SET_ALT", "Alt");
button_map.set("INTELLIMOUSE_PRO_BUTTON_SET_CTRL", "Ctrl");
button_map.set("INTELLIMOUSE_PRO_BUTTON_SET_SHIFT", "Shift");
button_map.set("INTELLIMOUSE_PRO_BUTTON_SET_ENTER", "Enter");
