package api

const (
	INTELLIMOUSE_PRO_PRODUCT_ID        = 0x082A
	INTELLIMOUSE_PRO_VENDOR_ID         = 0x045E
	INTELLIMOUSE_PRO_DPI_WRITE         = 0x96
	INTELLIMOUSE_PRO_DPI_READ          = INTELLIMOUSE_PRO_DPI_WRITE + 0x01
	INTELLIMOUSE_PRO_COLOR_WRITE       = 0xB2
	INTELLIMOUSE_PRO_COLOR_READ        = INTELLIMOUSE_PRO_COLOR_WRITE + 0x01
	INTELLIMOUSE_PRO_SET_REPORT        = 0x24
	INTELLIMOUSE_PRO_SET_REPORT_LENGTH = 0x49
	INTELLIMOUSE_PRO_GET_REPORT        = 0x27
	INTELLIMOUSE_PRO_GET_REPORT_LENGTH = 0x29
	INTELLIMOUSE_PRO_INTERFACE         = 0x01
	CLAMP_DPI_MULTIPLE                 = 50
	MOUSE_SLEEP_DRIVER_MILLISECONDS    = 1000
)
