package api

// Application specific
const (
	CLAMP_DPI_MULTIPLE              = 50
	MOUSE_SLEEP_DRIVER_MILLISECONDS = 1000
)

// intellimouse pro generic things
const (
	// uint16
	INTELLIMOUSE_PRO_PRODUCT_ID = 0x082A
	INTELLIMOUSE_PRO_VENDOR_ID  = 0x045E
	// uint8
	INTELLIMOUSE_PRO_SET_REPORT        = 0x24
	INTELLIMOUSE_PRO_SET_REPORT_LENGTH = 0x49
	INTELLIMOUSE_PRO_GET_REPORT        = 0x27
	INTELLIMOUSE_PRO_GET_REPORT_LENGTH = 0x29
	INTELLIMOUSE_PRO_INTERFACE         = 0x01
)

// intellimouse pro dpi things
const (
	// uint8
	INTELLIMOUSE_PRO_DPI_WRITE = 0x96
	INTELLIMOUSE_PRO_DPI_READ  = INTELLIMOUSE_PRO_DPI_WRITE + 0x01
)

// intellimouse pro color things
const (
	// uint8
	INTELLIMOUSE_PRO_COLOR_WRITE = 0xB2
	INTELLIMOUSE_PRO_COLOR_READ  = INTELLIMOUSE_PRO_COLOR_WRITE + 0x01
)

// For intellimouse pro button things
const (
	INTELLIMOUSE_PRO_BUTTON_WRITE = 0x88
	INTELLIMOUSE_PRO_BUTTON_READ  = INTELLIMOUSE_PRO_BUTTON_WRITE + 0x01

	INTELLIMOUSE_PRO_BACK_BUTTON = 0x04
	INTELLIMOUSE_PRO_MIDDLE_BUTTON = 0x03

	// uint32
	INTELLIMOUSE_PRO_BUTTON_SET_BACK_BUTTON                = 0x09000104
	INTELLIMOUSE_PRO_BUTTON_SET_HORIZONTAL_VERTICAL_TOGGLE = 0x09000203
	// 0x0409106 is also key combination
	// do not use this yet.
	// the key combination seems to go all the way from 0x0106 to 0x0200. If you fire with empty payload beyond 0x106,
	// the key combination gets reset to nothing
	// the 106, 107 etc has to do with the actual key combination and Im not sure what the heck that means
	// 0x0409501 is Key Combination (B)? wtf
	// 0x0409601 is Key combination C
	// 0x04091000 is Key Combination M
	// 0x04070100 is Key Lalt + M
	// so key combination is definetly 04 09 00 <106-200>, <205 ++>
	INTELLIMOUSE_PRO_BUTTON_SET_KEY_COMBINATION     = 0x09000200
	INTELLIMOUSE_PRO_BUTTON_SET_KEY_COMBINATION_TWO = 0x09000106
	INTELLIMOUSE_PRO_BUTTON_SET_DPI_SHIFT           = 0x09000204
	INTELLIMOUSE_PRO_BUTTON_SET_INCREASE_DPI        = 0x09000201
	INTELLIMOUSE_PRO_BUTTON_SET_DECREASE_DPI        = 0x09000202

	// Basic commands

	INTELLIMOUSE_PRO_BUTTON_SET_MIDDLE_CLICK    = 0x09000103
	INTELLIMOUSE_PRO_BUTTON_SET_BROWSER_FORWARD = 0x09000105
	INTELLIMOUSE_PRO_BUTTON_SET_ALT             = 0x07000000
	INTELLIMOUSE_PRO_BUTTON_SET_CTRL            = 0x07100000
	INTELLIMOUSE_PRO_BUTTON_SET_SHIFT           = 0x07200000
	INTELLIMOUSE_PRO_BUTTON_SET_ENTER           = 0x07002800
)


// map strings represented as constants. Might be useful for our frontend later.
const (
	INTELLIMOUSE_PRO_BUTTON_SET_BACK_BUTTON_STRING                = "INTELLIMOUSE_PRO_BUTTON_SET_BACK_BUTTON"
	INTELLIMOUSE_PRO_BUTTON_SET_HORIZONTAL_VERTICAL_TOGGLE_STRING = "INTELLIMOUSE_PRO_BUTTON_SET_HORIZONTAL_VERTICAL_TOGGLE"
	INTELLIMOUSE_PRO_BUTTON_SET_KEY_COMBINATION_STRING            = "INTELLIMOUSE_PRO_BUTTON_SET_KEY_COMBINATION"
	INTELLIMOUSE_PRO_BUTTON_SET_DPI_SHIFT_STRING                  = "INTELLIMOUSE_PRO_BUTTON_SET_DPI_SHIFT"
	INTELLIMOUSE_PRO_BUTTON_SET_INCREASE_DPI_STRING               = "INTELLIMOUSE_PRO_BUTTON_SET_INCREASE_DPI"
	INTELLIMOUSE_PRO_BUTTON_SET_DECREASE_DPI_STRING               = "INTELLIMOUSE_PRO_BUTTON_SET_DECREASE_DPI"
	INTELLIMOUSE_PRO_BUTTON_SET_MIDDLE_CLICK_STRING               = "INTELLIMOUSE_PRO_BUTTON_SET_MIDDLE_CLICK"
	INTELLIMOUSE_PRO_BUTTON_SET_BROWSER_FORWARD_STRING            = "INTELLIMOUSE_PRO_BUTTON_SET_BROWSER_FORWARD"
	INTELLIMOUSE_PRO_BUTTON_SET_ALT_STRING                        = "INTELLIMOUSE_PRO_BUTTON_SET_ALT"
	INTELLIMOUSE_PRO_BUTTON_SET_CTRL_STRING                       = "INTELLIMOUSE_PRO_BUTTON_SET_CTRL"
	INTELLIMOUSE_PRO_BUTTON_SET_SHIFT_STRING                      = "INTELLIMOUSE_PRO_BUTTON_SET_SHIFT"
	INTELLIMOUSE_PRO_BUTTON_SET_ENTER_STRING                      = "INTELLIMOUSE_PRO_BUTTON_SET_ENTER"
)

var ButtonMapping = map[string]uint32{
	INTELLIMOUSE_PRO_BUTTON_SET_BACK_BUTTON_STRING:                INTELLIMOUSE_PRO_BUTTON_SET_BACK_BUTTON,
	INTELLIMOUSE_PRO_BUTTON_SET_HORIZONTAL_VERTICAL_TOGGLE_STRING: INTELLIMOUSE_PRO_BUTTON_SET_HORIZONTAL_VERTICAL_TOGGLE,
	INTELLIMOUSE_PRO_BUTTON_SET_KEY_COMBINATION_STRING:            INTELLIMOUSE_PRO_BUTTON_SET_KEY_COMBINATION,
	INTELLIMOUSE_PRO_BUTTON_SET_DPI_SHIFT_STRING:                  INTELLIMOUSE_PRO_BUTTON_SET_DPI_SHIFT,
	INTELLIMOUSE_PRO_BUTTON_SET_INCREASE_DPI_STRING:               INTELLIMOUSE_PRO_BUTTON_SET_INCREASE_DPI,
	INTELLIMOUSE_PRO_BUTTON_SET_DECREASE_DPI_STRING:               INTELLIMOUSE_PRO_BUTTON_SET_DECREASE_DPI,
	INTELLIMOUSE_PRO_BUTTON_SET_MIDDLE_CLICK_STRING:               INTELLIMOUSE_PRO_BUTTON_SET_MIDDLE_CLICK,
	INTELLIMOUSE_PRO_BUTTON_SET_BROWSER_FORWARD_STRING:            INTELLIMOUSE_PRO_BUTTON_SET_BROWSER_FORWARD,
	INTELLIMOUSE_PRO_BUTTON_SET_ALT_STRING:                        INTELLIMOUSE_PRO_BUTTON_SET_ALT,
	INTELLIMOUSE_PRO_BUTTON_SET_CTRL_STRING:                       INTELLIMOUSE_PRO_BUTTON_SET_CTRL,
	INTELLIMOUSE_PRO_BUTTON_SET_SHIFT_STRING:                      INTELLIMOUSE_PRO_BUTTON_SET_SHIFT,
	INTELLIMOUSE_PRO_BUTTON_SET_ENTER_STRING:                      INTELLIMOUSE_PRO_BUTTON_SET_ENTER,
}
